name: .NET Build and Test

on:
  push:
    branches: 
      - "main"
      - "exercise-3"
    paths:
      - 'src/Application/**'
  pull_request:
    branches: 
      - "main"
    paths:
      - 'src/Application/**'

env:
  registryName: vs27w7ndcpge4mpnpreg.azurecr.io
  repositoryName: techexcel/dotnetcoreapp
  dockerFolderPath: ./src/Application/src/RazorPagesTestSample
  tag: ${{ github.run_number }}      

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
    - name: Build
      run: dotnet build --no-restore ./src/Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal ./src/Application/tests/RazorPagesTestSample.Tests/RazorPagesTestSample.Tests.csproj

  publish-image:

    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      uses: docker/login-action@v1.9.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ${{ secrets.ACR_LOGIN_SERVER }}
        # Username used to log against the Docker registry
        username: ${{ secrets.ACR_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.ACR_PASSWORD }}
        # Log out from the Docker registry at the end of a job
        logout: true

    - name: Docker build
      run: docker build -t ${{ env.registryName }}/${{ env.repositoryName }}:${{ env.tag }} --build-arg build_version=${{ env.tag }} ${{ env.dockerFolderPath }}

    - name: Docker push
      run: docker push ${{ env.registryName }}/${{ env.repositoryName }}:${{ env.tag }}

  deploy-dev-env:

    runs-on: ubuntu-latest
    needs: publish-image
    environment:
      name: dev
      url: https://vs27w7ndcpge4-mpnp-webapp-dev.azurewebsites.net/
    
    steps:
      - uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v2.1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'vs27w7ndcpge4-mpnp-webapp-dev'
          images: vs27w7ndcpge4mpnpreg.azurecr.io/techexcel/dotnetcoreapp:${{ env.tag }}

  deploy-test-env:
    runs-on: ubuntu-latest
    needs: deploy-dev-env
    environment:
      name: test
      url: https://vs27w7ndcpge4-mpnp-webapp-test.azurewebsites.net
    steps:
    - uses: actions/checkout@v3

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Update Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: vs27w7ndcpge4-mpnp-webapp-test
        images: vs27w7ndcpge4mpnpreg.azurecr.io/techexcel/dotnetcoreapp:${{ env.tag }}
    - name: Azure logout
      run: az logout

  deploy-prod-env:
    runs-on: ubuntu-latest
    needs: deploy-test-env
    environment:
      name: prod
      url: https://vs27w7ndcpge4-mpnp-webapp-prod.azurewebsites.net
    steps:
    - uses: actions/checkout@v3

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Update Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: vs27w7ndcpge4-mpnp-webapp-prod
        images: vs27w7ndcpge4mpnpreg.azurecr.io/techexcel/dotnetcoreapp:${{ env.tag }}

    - name: Azure logout
      run: az logout      